"""
SQL для таблиц: MP_POSTINGS, MP_SUPPLIES, AP_LOGS, CASHSALES.
Позиционные параметры ? (dt_from, dt_from, dt_to, dt_to [и опционально status]).
"""
# Период: 4 параметра (dt_from, dt_from, dt_to, dt_to)

# --- MP_POSTINGS (отправления маркетплейса). Поле даты: CREATE_TIME (если нет — проверьте list_columns MP_POSTINGS) ---
MP_POSTINGS_COUNT_SQL = """
SELECT COUNT(*) AS cnt
FROM MP_POSTINGS p
WHERE (? IS NULL OR CAST(p.CREATE_TIME AS DATE) >= ?)
  AND (? IS NULL OR CAST(p.CREATE_TIME AS DATE) <= ?)
  AND (? IS NULL OR p.STATUS = ?)
"""

MP_POSTINGS_BY_DAY_SQL = """
SELECT CAST(p.CREATE_TIME AS DATE) AS day_date, COUNT(*) AS cnt
FROM MP_POSTINGS p
WHERE (? IS NULL OR CAST(p.CREATE_TIME AS DATE) >= ?)
  AND (? IS NULL OR CAST(p.CREATE_TIME AS DATE) <= ?)
GROUP BY CAST(p.CREATE_TIME AS DATE)
ORDER BY day_date
"""

MP_POSTINGS_BY_STATUS_SQL = """
SELECT p.STATUS AS status, COUNT(*) AS cnt
FROM MP_POSTINGS p
WHERE (? IS NULL OR CAST(p.CREATE_TIME AS DATE) >= ?)
  AND (? IS NULL OR CAST(p.CREATE_TIME AS DATE) <= ?)
GROUP BY p.STATUS
ORDER BY cnt DESC
"""

# Список отправлений с face_name (FACES)
MP_POSTINGS_LIST_SQL = """
SELECT FIRST 200
  p.POSTING_NUMBER, p.FACE_ID, p.MP_ID, p.CREATE_TIME, p.NAME AS posting_name,
  p.ISDONE, p.ISLARGECARGO,
  f.NAME AS face_name, f.SHORTNAME AS face_shortname
FROM MP_POSTINGS p
LEFT JOIN FACES f ON p.FACE_ID = f.ID
WHERE (? IS NULL OR CAST(p.CREATE_TIME AS DATE) >= ?)
  AND (? IS NULL OR CAST(p.CREATE_TIME AS DATE) <= ?)
ORDER BY p.CREATE_TIME DESC
"""

# --- MP_SUPPLIES (поставки) ---
MP_SUPPLIES_COUNT_SQL = """
SELECT COUNT(*) AS cnt
FROM MP_SUPPLIES s
WHERE (? IS NULL OR CAST(s.CREATE_TIME AS DATE) >= ?)
  AND (? IS NULL OR CAST(s.CREATE_TIME AS DATE) <= ?)
"""

MP_SUPPLIES_BY_DAY_SQL = """
SELECT CAST(s.CREATE_TIME AS DATE) AS day_date, COUNT(*) AS cnt
FROM MP_SUPPLIES s
WHERE (? IS NULL OR CAST(s.CREATE_TIME AS DATE) >= ?)
  AND (? IS NULL OR CAST(s.CREATE_TIME AS DATE) <= ?)
GROUP BY CAST(s.CREATE_TIME AS DATE)
ORDER BY day_date
"""

# Список поставок с face_name (FACES)
MP_SUPPLIES_LIST_SQL = """
SELECT FIRST 200
  s.ID, s.CODE, s.FACE_ID, s.NAME AS supply_name, s.ISDONE, s.ISLARGECARGO,
  s.MP_CREATE_TIME, s.MP_CLOSED_TIME, s.CREATE_TIME,
  f.NAME AS face_name, f.SHORTNAME AS face_shortname
FROM MP_SUPPLIES s
LEFT JOIN FACES f ON s.FACE_ID = f.ID
WHERE (? IS NULL OR CAST(s.CREATE_TIME AS DATE) >= ?)
  AND (? IS NULL OR CAST(s.CREATE_TIME AS DATE) <= ?)
ORDER BY s.CREATE_TIME DESC
"""

# --- AP_LOGS (логи приложения) ---
AP_LOGS_COUNT_SQL = """
SELECT COUNT(*) AS cnt
FROM AP_LOGS a
WHERE (? IS NULL OR CAST(a.CREATE_TIME AS DATE) >= ?)
  AND (? IS NULL OR CAST(a.CREATE_TIME AS DATE) <= ?)
"""

AP_LOGS_BY_DAY_SQL = """
SELECT CAST(a.CREATE_TIME AS DATE) AS day_date, COUNT(*) AS cnt
FROM AP_LOGS a
WHERE (? IS NULL OR CAST(a.CREATE_TIME AS DATE) >= ?)
  AND (? IS NULL OR CAST(a.CREATE_TIME AS DATE) <= ?)
GROUP BY CAST(a.CREATE_TIME AS DATE)
ORDER BY day_date
"""

# --- CASHSALES (продажи по кассе). Поле даты: CREATE_TIME (если нет — проверьте list_columns CASHSALES) ---
CASHSALES_COUNT_SQL = """
SELECT COUNT(*) AS cnt
FROM CASHSALES c
WHERE (? IS NULL OR CAST(c.CREATE_TIME AS DATE) >= ?)
  AND (? IS NULL OR CAST(c.CREATE_TIME AS DATE) <= ?)
"""

CASHSALES_BY_DAY_SQL = """
SELECT CAST(c.CREATE_TIME AS DATE) AS day_date, COUNT(*) AS cnt
FROM CASHSALES c
WHERE (? IS NULL OR CAST(c.CREATE_TIME AS DATE) >= ?)
  AND (? IS NULL OR CAST(c.CREATE_TIME AS DATE) <= ?)
GROUP BY CAST(c.CREATE_TIME AS DATE)
ORDER BY day_date
"""
