"""
Вызовы хранимых процедур Firebird (selectable: SELECT * FROM proc(...)).
Сигнатуры:
  RPT_PAYS(TASK_ID INTEGER) RETURNS (...)
  RPT_PAYSPERIOD(TASK_ID INTEGER, DTLO DATE, DTHI DATE, CURRENCY_N INTEGER, CURRENCY_ID INTEGER, CURRENCYRND INTEGER) RETURNS (...)
  DOC_TOTALIZE(DOC_ID INTEGER, FLAGS INTEGER) — executable, без RETURNS
  DOC_CALCSUMTOPAY(DOC_ID INTEGER, PAYHASNP SMALLINT, CRCRND_N INTEGER) RETURNS (...)
  DOC_PAY_LIST(D_ID INTEGER, SMJ_MODE INTEGER) RETURNS (...)
"""
# RPT_PAYS: 1 параметр
RPT_PAYS_SQL = "SELECT * FROM RPT_PAYS(?)"

# RPT_PAYSPERIOD: 6 параметров (TASK_ID, DTLO, DTHI, CURRENCY_N, CURRENCY_ID, CURRENCYRND)
RPT_PAYSPERIOD_SQL = "SELECT * FROM RPT_PAYSPERIOD(?, ?, ?, ?, ?, ?)"

# DOC_TOTALIZE: исполняемая процедура, без возврата строк (EXECUTE PROCEDURE)
DOC_TOTALIZE_EXEC_SQL = "EXECUTE PROCEDURE DOC_TOTALIZE(?, ?)"

# DOC_CALCSUMTOPAY: 3 параметра
DOC_CALCSUMTOPAY_SQL = "SELECT * FROM DOC_CALCSUMTOPAY(?, ?, ?)"

# DOC_PAY_LIST: 2 параметра (D_ID, SMJ_MODE)
DOC_PAY_LIST_SQL = "SELECT * FROM DOC_PAY_LIST(?, ?)"

PROC_NAMES = ['RPT_PAYSPERIOD', 'RPT_PAYS', 'DOC_TOTALIZE', 'DOC_PAY_LIST', 'DOC_CALCSUMTOPAY']
